# postgresql-deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mlops # Ensure this is in the same namespace as MLflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # You can adjust this size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mlops
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15 # Use a specific version, e.g., 15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: mlflowdb # Name of the database for MLflow
            - name: POSTGRES_USER
              value: mlflowuser # Database user
            - name: POSTGRES_PASSWORD
              value: mlflowpassword # Database password (use a strong one in prod!)
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlops
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP