apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-access-binding
  namespace: mlops
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
    namespace: kubeflow
roleRef:
  kind: Role
  name: pipeline-access
  apiGroup: rbac.authorization.k8s.io