apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-access
  namespace: mlops
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "patch"]
