apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-news-app
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-news-app
  template:
    metadata:
      labels:
        app: streamlit-news-app
    spec:
      containers:
      - name: streamlit
        image: streamlit-news-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-news-app
  namespace: kubeflow
spec:
  selector:
    app: streamlit-news-app
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 31001
  type: NodePort
