apiVersion: v1
kind: Service
metadata:
  name: bentoml-news
  namespace: kubeflow
spec:
  type: NodePort
  selector:
    app: bentoml-news
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
